### ISSUE TITLE
1.6.0 doesn't compile with gcc 4.8.1

### ISSUE THREAD

**Issue by v4hn** [OctoMap/octomap#34]
Heya,

v1.6.0 produces the following error over here:

```
/home/v4hn/repos/octomap/octomap/include/octomap/OcTreeBaseImpl.h: In instantiation of 'class octomap::OcTreeBaseImpl<octomap::OcTreeNode, octomap::AbstractOccupancyOcTree>':
/home/v4hn/repos/octomap/octomap/include/octomap/OccupancyOcTreeBase.h:68:9:   required from 'class octomap::OccupancyOcTreeBase<octomap::OcTreeNode>'
/home/v4hn/repos/octomap/octomap/include/octomap/OcTree.h:49:25:   required from here
/home/v4hn/repos/octomap/octomap/include/octomap/OcTreeBaseImpl.h:149:20: error: cannot allocate an object of abstract type 'octomap::OcTreeBaseImpl<octomap::OcTreeNode, octomap::AbstractOccupancyOcTree>'
     OcTreeBaseImpl deepCopy() const;
```

This bug was fixed in April in commit f19a23d33880fb60b51277ee5e02fef3ade7fbd1
by removing that function. However, there has not been a new (bug fix) release since then.
I would very much like to see an official version that fixes that (probably as well as other)
problems.
